export function copySummary(summaryData) {
  let text = '';

  // Add title
  text += 'MEDICAL REPORT SUMMARY\n';
  text += '='.repeat(50) + '\n\n';

  // Add medical summary
  if (summaryData.summary) {
    text += 'MEDICAL SUMMARY\n';
    text += '-'.repeat(50) + '\n';
    text += summaryData.summary + '\n\n';
  }

  // Add plain language explanation
  if (summaryData.explanation && summaryData.explanation.length > 0) {
    text += 'PLAIN LANGUAGE EXPLANATION\n';
    text += '-'.repeat(50) + '\n';
    summaryData.explanation.forEach(item => {
      text += `• ${item.title}\n`;
      if (item.description) {
        text += `  ${item.description}\n`;
      }
    });
    text += '\n';
  }

  // Add findings
  if (summaryData.findings && summaryData.findings.length > 0) {
    text += 'IMPORTANT FINDINGS\n';
    text += '-'.repeat(50) + '\n';
    summaryData.findings.forEach(finding => {
      text += `${finding.name}: ${finding.value} (${finding.status})\n`;
      if (finding.description) {
        text += `  ${finding.description}\n`;
      }
    });
    text += '\n';
  }

  // Add doctor note
  if (summaryData.doctor_note) {
    text += 'DOCTOR RECOMMENDATION\n';
    text += '-'.repeat(50) + '\n';
    text += summaryData.doctor_note + '\n\n';
  }

  // Add health score
  if (summaryData.health_score) {
    text += `HEALTH SCORE: ${summaryData.health_score}/100\n`;
  }

  text += '\n' + '='.repeat(50) + '\n';
  text += 'Generated by ReportEase - Medical AI Analysis\n';

  navigator.clipboard.writeText(text).then(() => {
    return true;
  }).catch(() => {
    console.error('Failed to copy to clipboard');
    return false;
  });
}
