export function copyTranslation(translationData, language = 'en') {
  let text = '';

  if (translationData.report_name) {
    text += `Report: ${translationData.report_name}\n`;
  }
  if (translationData.report_date) {
    text += `Date: ${translationData.report_date}\n`;
  }
  if (translationData.patient_name) {
    text += `Patient: ${translationData.patient_name}\n`;
  }

  text += '\n' + '='.repeat(60) + '\n\n';

  // Add medical summary
  if (translationData.summary) {
    text += 'MEDICAL SUMMARY\n';
    text += '-'.repeat(60) + '\n';
    text += translationData.summary + '\n\n';
  }

  // Add explanations
  if (translationData.explanations && translationData.explanations.length > 0) {
    text += 'WHAT THIS MEANS FOR YOU\n';
    text += '-'.repeat(60) + '\n';
    translationData.explanations.forEach((item, index) => {
      text += `${index + 1}. ${item.title}\n`;
      if (item.description) {
        text += `   ${item.description}\n`;
      }
      text += '\n';
    });
    text += '\n';
  }

  // Add recommendation
  if (translationData.recommendation) {
    text += 'DOCTOR RECOMMENDATION\n';
    text += '-'.repeat(60) + '\n';
    text += translationData.recommendation + '\n\n';
  }

  text += '='.repeat(60) + '\n';
  text += 'Generated by ReportEase - Medical AI Translation\n';

  navigator.clipboard.writeText(text).then(() => {
    return true;
  }).catch(() => {
    console.error('Failed to copy to clipboard');
    return false;
  });
}
