export function downloadTranslation(translationData, language = 'en', languageName = 'English') {
  let text = '';

  // Add title
  text += 'MEDICAL REPORT TRANSLATION\n';
  text += `Language: ${languageName}\n`;
  text += '='.repeat(60) + '\n\n';

  // Add report meta
  if (translationData.report_name) {
    text += `Report: ${translationData.report_name}\n`;
  }
  if (translationData.report_date) {
    text += `Date: ${translationData.report_date}\n`;
  }
  if (translationData.patient_name) {
    text += `Patient: ${translationData.patient_name}\n`;
  }

  text += '\n' + '='.repeat(60) + '\n\n';

  // Add medical summary
  if (translationData.summary) {
    text += 'MEDICAL SUMMARY\n';
    text += '-'.repeat(60) + '\n';
    text += translationData.summary + '\n\n';
  }

  // Add explanations
  if (translationData.explanations && translationData.explanations.length > 0) {
    text += 'WHAT THIS MEANS FOR YOU\n';
    text += '-'.repeat(60) + '\n';
    translationData.explanations.forEach((item, index) => {
      text += `${index + 1}. ${item.title}\n`;
      if (item.description) {
        text += `   ${item.description}\n`;
      }
      text += '\n';
    });
  }

  // Add recommendation
  if (translationData.recommendation) {
    text += '\nDOCTOR RECOMMENDATION\n';
    text += '-'.repeat(60) + '\n';
    text += translationData.recommendation + '\n\n';
  }

  text += '='.repeat(60) + '\n';
  text += 'Generated by ReportEase - Medical AI Translation\n';
  text += 'Please consult with your healthcare provider for medical advice.\n';

  // Create and trigger download
  const element = document.createElement('a');
  const file = new Blob([text], { type: 'text/plain; charset=utf-8' });
  element.href = URL.createObjectURL(file);
  element.download = `translation_${language}_${new Date().toISOString().split('T')[0]}.txt`;
  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
  URL.revokeObjectURL(element.href);
}
