export function downloadSummary(summaryData, reportName = 'medical_report_summary') {
  let text = '';

  // Add title
  text += 'MEDICAL REPORT SUMMARY\n';
  text += '='.repeat(60) + '\n\n';

  // Add report meta information
  if (summaryData.report_name) {
    text += `Report: ${summaryData.report_name}\n`;
  }
  if (summaryData.report_date) {
    text += `Date: ${summaryData.report_date}\n`;
  }
  if (summaryData.patient_name) {
    text += `Patient: ${summaryData.patient_name}\n`;
  }
  if (summaryData.report_type) {
    text += `Type: ${summaryData.report_type}\n`;
  }
  text += '\n' + '='.repeat(60) + '\n\n';

  // Add medical summary
  if (summaryData.summary) {
    text += 'MEDICAL SUMMARY\n';
    text += '-'.repeat(60) + '\n';
    text += summaryData.summary + '\n\n';
  }

  // Add plain language explanation
  if (summaryData.explanation && summaryData.explanation.length > 0) {
    text += 'WHAT THIS MEANS FOR YOU\n';
    text += '-'.repeat(60) + '\n';
    summaryData.explanation.forEach((item, index) => {
      text += `${index + 1}. ${item.title}\n`;
      if (item.description) {
        text += `   ${item.description}\n`;
      }
      text += '\n';
    });
    text += '\n';
  }

  // Add findings
  if (summaryData.findings && summaryData.findings.length > 0) {
    text += 'IMPORTANT FINDINGS\n';
    text += '-'.repeat(60) + '\n';
    text += 'Test Name | Value | Status | Reference Range\n';
    text += '-'.repeat(60) + '\n';
    summaryData.findings.forEach(finding => {
      const refRange = finding.reference_range ? ` (${finding.reference_range})` : '';
      text += `${finding.name} | ${finding.value} | ${finding.status}${refRange}\n`;
      if (finding.description) {
        text += `  Note: ${finding.description}\n`;
      }
    });
    text += '\n';
  }

  // Add doctor note
  if (summaryData.doctor_note) {
    text += 'DOCTOR RECOMMENDATION\n';
    text += '-'.repeat(60) + '\n';
    text += summaryData.doctor_note + '\n\n';
  }

  // Add health score
  if (summaryData.health_score) {
    text += `OVERALL HEALTH SCORE: ${summaryData.health_score}/100\n`;
    const category = getHealthCategory(summaryData.health_score);
    text += `Status: ${category}\n\n`;
  }

  // Add key values if available
  if (summaryData.key_values) {
    text += 'KEY VALUES\n';
    text += '-'.repeat(60) + '\n';
    Object.entries(summaryData.key_values).forEach(([key, value]) => {
      text += `${key}: ${value}\n`;
    });
    text += '\n';
  }

  text += '='.repeat(60) + '\n';
  text += 'Generated by ReportEase - AI-Powered Medical Report Analysis\n';
  text += 'This summary is for informational purposes only.\n';
  text += 'Please consult with your healthcare provider for medical advice.\n';

  // Create blob and download
  const element = document.createElement('a');
  const file = new Blob([text], { type: 'text/plain' });
  element.href = URL.createObjectURL(file);
  element.download = `${reportName}_${new Date().toISOString().split('T')[0]}.txt`;
  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
  URL.revokeObjectURL(element.href);
}

function getHealthCategory(score) {
  if (score >= 80) return 'Excellent';
  if (score >= 60) return 'Moderate';
  if (score >= 40) return 'Fair';
  return 'Needs Attention';
}
